apiVersion: v1
kind: Service
metadata:
  name: parser-service
spec:
  type: ClusterIP
  selector:
    app: parser
  ports:
    - protocol: TCP
      port: 8080       # Внутренний порт сервиса в кластере
      targetPort: 8080 # Порт на нашем контейнере (из deployment.yaml)