apiVersion: v1
kind: Service
metadata:
  name: rosreestr-service # Имя, по которому другие поды будут обращаться к API
spec:
  selector:
    app: rosreestr-service # ТОЧНО ТАКОЙ ЖЕ селектор, как в Deployment
  ports:
    - protocol: TCP
      port: 80 # Порт, который "слушает" сам сервис
      targetPort: 8000 # Порт, на который перенаправляется трафик (порт uvicorn)
